// layout.js
import { Montserrat } from "next/font/google";
import Navbar from './component/navbar/navbar';
import Footer from './component/Footer/Footer';
import { Ubuntu } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // jitni chahiye
  variable: "--font-montserrat", // CSS variable
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // jitni chahiye
  variable: "--font-ubuntu", // CSS variable
});

export const metadata = {
  title: "Varium AI Car",
  description: "Generated by Next.js",
   icons: {
    icon: "/logo/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${ubuntu.variable} antialiased`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
